# Generated by Django 5.1.4 on 2024-12-21 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RistorantiRicetteIngredienti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='name_text',
            field=models.CharField(default='test ingrediente', max_length=200),
        ),
        migrations.AddField(
            model_name='ricetta',
            name='name_text',
            field=models.CharField(default='test ricetta', max_length=5000),
        ),
        migrations.AddField(
            model_name='ristorante',
            name='name_text',
            field=models.CharField(default='test ristorante', max_length=200),
        ),
        migrations.CreateModel(
            name='RicettaToIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RistorantiRicetteIngredienti.ingrediente')),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RistorantiRicetteIngredienti.ricetta')),
            ],
        ),
        migrations.CreateModel(
            name='RistoranteToRicetta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RistorantiRicetteIngredienti.ricetta')),
                ('ristorante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RistorantiRicetteIngredienti.ristorante')),
            ],
        ),
    ]
