# Generated by Django 5.1.4 on 2024-12-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RistorantiRicetteIngredienti', '0002_ingrediente_name_text_ricetta_name_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'verbose_name_plural': 'Ingredienti'},
        ),
        migrations.AlterModelOptions(
            name='ricetta',
            options={'verbose_name_plural': 'Ricette'},
        ),
        migrations.AlterModelOptions(
            name='ristorante',
            options={'verbose_name_plural': 'Ristoranti'},
        ),
        migrations.RenameField(
            model_name='ingrediente',
            old_name='name_text',
            new_name='ingrediente_text',
        ),
        migrations.RenameField(
            model_name='ricetta',
            old_name='name_text',
            new_name='ricetta_text',
        ),
        migrations.RenameField(
            model_name='ristorante',
            old_name='name_text',
            new_name='ristorante_text',
        ),
    ]
