# Generated by Django 5.1.4 on 2024-12-22 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RistorantiRicetteIngredienti', '0003_alter_ingrediente_options_alter_ricetta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ristorantetoricetta',
            name='ricetta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ristorantetoricetta', to='RistorantiRicetteIngredienti.ricetta'),
        ),
        migrations.AlterField(
            model_name='ristorantetoricetta',
            name='ristorante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ristorantetoricetta', to='RistorantiRicetteIngredienti.ristorante'),
        ),
    ]
